name: PRD | Discord Bot Moriarty - Code Challenges
on:
  push:
    branches:
      - deployment
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_DEPLOY_HOST }}
          port: ${{ secrets.SERVER_DEPLOY_PORT }}
          username: ${{ secrets.SERVER_DEPLOY_USER }}
          password: ${{ secrets.SERVER_DEPLOY_PASSWORD }}
          scp_source: ./*
          scp_target: /var/www/${{secrets.SERVER_FOLDER_LOCATION}}
          before_script: |
            mkdir -p "/var/www/${{secrets.SERVER_FOLDER_LOCATION}}"
            find /var/www/${{secrets.SERVER_FOLDER_LOCATION}} -type f -not -name '*.env'-delete
          after_script: |
            cd /var/www/${{secrets.SERVER_FOLDER_LOCATION}} && docker-compose stop && docker-compose build && docker-compose up -d